### PR TITLE
Makefile: select good sed on mac

### PR DESCRIPTION
**Pull request by nicollet**

### CODE REVIEW

**Comment by jkrauska** [comment]
gsed is not a osx built in, but typically a brew add on instead..  I'm not sure it's safe to assume everyone has it...  maybe better to find the equivalent sed flags with bsd sed to get the same output -- and parameterize $SED_FLAGS ?

**Comment by jkrauska** [comment]
does go - net - ParseIP do this more cleanly?

https://golang.org/pkg/net/#ParseIP

**Comment by nicollet** [comment]
- sed: this would work for those who have GNU sed. So applying this would make it better for them at least. Agreed that we could make it even more portable.

- Prints IPv4: I should have put it on another branch as I didn't want it to be part of this pull request sorry about that. Will rebase/push.

**Comment by jfesler** [comment]
Another option: a separate (bundled) simple go file that does what sed does now.

**Comment by stfp** [comment]
Superseded by #10
Thanks!

**Pull request closed without merging**
